// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/auth_app/app/models"

// ServiceUser is an autogenerated mock type for the ServiceUser type
type ServiceUser struct {
	mock.Mock
}

// Login provides a mock function with given fields: user
func (_m *ServiceUser) Login(user *models.User) (*string, error) {
	ret := _m.Called(user)

	var r0 *string
	if rf, ok := ret.Get(0).(func(*models.User) *string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: user
func (_m *ServiceUser) RegisterUser(user *models.User) (*string, error) {
	ret := _m.Called(user)

	var r0 *string
	if rf, ok := ret.Get(0).(func(*models.User) *string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
